#!/usr/bin/env python
""" genHCPURTemplate

Python command line interface for MRTrix3 multi-shell multi-tissue
constrained spherical deconvolution tractography pipeline with Dhollander
response function

"""
def get_parser():
    """
    Argument parser
    """
    from argparse import ArgumentParser, RawTextHelpFormatter
    from mrtpipelines._version import __version__

    parser = ArgumentParser(description="Pipeline to generate MRTrix3 "
                                        "multi-shell multi-tissue CSD "
                                        "tractography with Dhollander "
                                        "response",
                            formatter_class=RawTextHelpFormatter)

    # Version option
    parser.add_argument("-v", "--version", dest="version",
                        action="version", version=__version__)

    # Required arguments
    g_req = parser.add_argument_group("Required arguments")
    g_req.add_argument("bids_dir", help="Directory with input dataset, "
                                        "formatted according to the BIDS "
                                        "standard.")
    g_req.add_argument('participant_label', help="A file containing label(s) "
                                                 "of participant(s) to perform "
                                                 "pipeline execution on")

    # Optional arguments
    g_opt = parser.add_argument_group("Optional arguments")
    g_opt.add_argument("-N", "--select", dest="select", default=25000,
                                         help="Number of streamlines to "
                                              "generate for each subject. "
                                              "Defaults 100,000 streamlines")
    g_opt.add_argument("-s", "--shells", dest="shells", default=[0, 1000, 2000],
                                         nargs="+", type=float,
                                         help="b-values to use during "
                                              "processing of fiber oreintation "
                                              "distribution computation "
                                              "(eg. --shells 0 1000 2000)")
    g_opt.add_argument("-l", "--lmax", dest="lmax", default=[0, 8, 8],
                                       nargs='+', type=int,
                                       help="maximum harmonic degree(s) for "
                                            "response function estimation "
                                            "(eg. --lmax 0 8 8)")
    g_opt.add_argument("-w", "--work_dir", dest="work_dir",
                                           help="Work directory. Defaults to "
                                           "<bids_dir>/derivatives/MRtrix/work")
    g_opt.add_argument("-o", "--out_dir", dest="out_dir",
                                          help="Output directory. Defaults to "
                                           "<bids_dir>/derivatives/MRtrix")
    g_opt.add_argument("-n", "--nthreads", dest="nthreads", default=1,
                                           help="The number of threads to use "
                                           "for pipeline execution where "
                                           "applicable.")

    return parser


def main():
    """
    Entry point of code
    """
    import os
    import os.path as op

    from bids.layout import BIDSLayout
    # MRTrix subject tractography generation workflow
    from nipype import config, logging
    from nipype.pipeline import engine as pe

    from mrtpipelines.interfaces import io
    from mrtpipelines.workflows import (population_wf, preproc_wf,
                                        tractography_wf)

    args = get_parser().parse_args()

    # Required inputs
    bids_dir = args.bids_dir
    deriv_dir = op.join(op.realpath(bids_dir), "derivatives")
    subjids = args.participant_label
    shells = args.shells
    lmax = args.lmax
    nfibers = int(args.select)
    nthreads = int(args.nthreads)

    # Set work & crash directories
    if args.work_dir:
        work_dir = op.realpath(args.work_dir)
        crash_dir = op.join(op.realpath(args.work_dir), "crash")
    else:
        work_dir = op.join(bids_dir, "derivatives/MRtrix/work")
        crash_dir = op.join(op.realpath(bids_dir, "derivatives/crash"))

    if not op.exists(work_dir):
        os.makedirs(work_dir)
    if not op.exists(crash_dir):
        os.makedirs(crash_dir)

    if args.out_dir:
        out_dir = op.realpath(args.out_dir)
    else:
        out_dir = op.join(deriv_dir, 'MRtrix')

    config.update_config({'logging': {'log_directory': work_dir,
                                      'log_to_file': True,
                                      },
                          'execution': {'crashdump_dir': crash_dir,
                                        'crashfile_format': 'txt'
                                        }})
    logging.update_logging(config)

    # getSubj
    Subjid, noSubj = io.getSubj(subjids, work_dir, nthreads=nthreads)

    # Create necessary nodes not part of existing workflows
    # BIDSDataGrabber
    layout = BIDSLayout(bids_dir)
    BIDSDataGrabber = io.getBIDS(layout=layout, wdir=work_dir,
                                 nthreads=nthreads)

    # MRTrix preprocessing workflow
    hcp_preproc_wf = preproc_wf.preproc_wf(shells=shells, lmax=lmax,
                                           wdir=work_dir, nthreads=nthreads)

    prepAnat_wf = preproc_wf.prepAnat_wf(wdir=work_dir, nthreads=nthreads)

    # MRTrix population template workflow
    fodTemplate_wf = population_wf.fodTemplate_wf(wdir=work_dir,
                                                  nthreads=nthreads)

    tensorTemplate_wf = population_wf.tensorTemplate_wf(wdir=work_dir,
                                                        nthreads=nthreads)

    anatTemplate_wf = population_wf.anatTemplate_wf(wdir=work_dir,
                                                   nthreads=nthreads)

    # MRTrix tractography/tensor workflow
    prepTensor_wf = preproc_wf.prepTensor_wf(wdir=work_dir, nthreads=nthreads)

    # MRTrix tractography generation workflow
    genTemplateTract_wf = tractography_wf.genTemplateTract_wf(wdir=work_dir,
                                                              nfibers=nfibers,
                                                              nthreads=nthreads)

    # Template datasink
    templateSink = io.templateSink(out_dir, wdir=work_dir, nthreads=nthreads)

    # Rename nodes for subject sinking
    renameWarp1 = io.renameFile(file_name='space-Template_warp',
                                node_name='renameWarp1', wdir=work_dir,
                                nthreads=nthreads)

    renameWarp2 = io.renameFile(file_name='space-T1w_warp',
                                node_name='renameWarp2', wdir=work_dir,
                                nthreads=nthreads)

    renameMask = io.renameFile(file_name='space-Template_brainmask',
                               node_name='renameMask', wdir=work_dir,
                               nthreads=nthreads)

    renameDWINorm = io.renameFile(file_name='space-Template_normalize',
                                  node_name='renameDWINorm', wdir=work_dir,
                                  nthreads=nthreads)

    renameDTI = io.renameFile(file_name='space-Template_tensor',
                              node_name='renameDTI', wdir=work_dir,
                              nthreads=nthreads)

    renameFA = io.renameFile(file_name='space-Template_fa',
                             node_name='renameFA', wdir=work_dir,
                             nthreads=nthreads)

    renameMD = io.renameFile(file_name='space-Template_md',
                             node_name='renameMD', wdir=work_dir,
                             nthreads=nthreads)

    renameAD = io.renameFile(file_name='space-Template_ad',
                             node_name='renameAD', wdir=work_dir,
                             nthreads=nthreads)

    renameRD = io.renameFile(file_name='space-Template_rd',
                             node_name='renameRD', wdir=work_dir,
                             nthreads=nthreads)

    renameT1w = io.renameFile(file_name='space-Template_T1w',
                              node_name='renameT1w', wdir=work_dir,
                              nthreads=nthreads)

    renameT2w = io.renameFile(file_name='space-Template_T2w',
                              node_name='renameT2w', wdir=work_dir,
                              nthreads=nthreads)

    # Subject datasink
    subjSink = io.subjSink(out_dir, wdir=work_dir, nthreads=nthreads)
    regex_sub = [('_subjid_sub-[0-9]*', ''),
                ('_renameWarp[0-9]*', ''),
                ('_renameAD[0-9]*', ''),
                ('_renameDTI[0-9]*', ''),
                ('_renameFA[0-9]*', ''),
                ('_renameMD[0-9]*', ''),
                ('_renameRD[0-9]*', ''),
                ('_renameDWINorm[0-9]*', ''),
                ('_renameMask[0-9]*', ''),
                ('_renameT1w[0-9]*', ''),
                ('_renameT2w[0-9]*', '')]
    subjSink.inputs.regexp_substitutions = regex_sub

    # Pipeline creation (join nodes and workflows)
    pl = pe.Workflow(name='genHCPTemplate')
    pl.base_dir = work_dir

    pl.connect([
                # Input
                (Subjid, BIDSDataGrabber, [
                    ('subjid', 'subjid')]),
                (BIDSDataGrabber, hcp_preproc_wf, [
                    ('dwi', 'dwiConvert.in_file'),
                    ('bdata', 'dwiConvert.grad_fsl'),
                    ('bdata', 'dwi2response.grad_fsl'),
                    ('mask', 'maskConvert.in_file')]),
                (BIDSDataGrabber, prepAnat_wf, [
                    ('t1w', 't1wConvert.in_file'),
                    ('t2w', 't2wConvert.in_file')]),

                # Diffusion / tractography Workflows
                (hcp_preproc_wf, fodTemplate_wf, [
                    ('dwi2response.gm_file', 'avgResponse_gm.in_files'),
                    ('dwi2response.wm_file', 'avgResponse_wm.in_files'),
                    ('dwi2response.csf_file', 'avgResponse_csf.in_files'),
                    ('dwiConvert.out_file', 'dwi2fod.in_file'),
                    ('maskConvert.out_file', 'mtnormalise.mask'),
                    ('maskConvert.out_file', 'copyMask.in_file')]),
                (fodTemplate_wf, prepTensor_wf, [
                    ('dwi2fod.wm_odf', 'MRRegister.in_file'),
                    ('FODTemplate.out_file', 'MRRegister.ref_file')]),
                (hcp_preproc_wf, prepTensor_wf, [
                    ('maskConvert.out_file', 'MRRegister.mask1'),
                    ('maskConvert.out_file', 'MaskTransform.in_file'),
                    ('dwiConvert.out_file', 'DWINormalise.in_file'),
                    ('maskConvert.out_file', 'DWINormalise.in_mask')]),
                (prepTensor_wf, tensorTemplate_wf, [
                    ('MaskTransform.out_file', 'copyTempMask.in_file'),
                    ('TensorMetrics.out_fa', 'copyFA.in_file'),
                    ('TensorMetrics.out_adc', 'copyMD.in_file'),
                    ('TensorMetrics.out_ad', 'copyAD.in_file'),
                    ('TensorMetrics.out_rd', 'copyRD.in_file')]),
                (fodTemplate_wf, genTemplateTract_wf, [
                    ('FODTemplate.out_file', 'template_tckgen.in_file'),
                    ('FODTemplate.out_file', 'template_tcksift.in_fod')]),
                (tensorTemplate_wf, genTemplateTract_wf, [
                    ('MaskTemplate.out_file', 'template_tckgen.seed_image')]),

                # Anatomical workflows
                (prepTensor_wf, prepAnat_wf, [
                    ('WarpSelect1.out', 't1wTransform.warp'),
                    ('WarpSelect1.out', 't2wTransform.warp')]),
                (prepAnat_wf, anatTemplate_wf, [
                    ('t1wTransform.out_file', 'copyT1w.in_file'),
                    ('t2wTransform.out_file', 'copyT2w.in_file')]),
                (tensorTemplate_wf, anatTemplate_wf, [
                    ('copyTempMask.out_dir', 'T1wTemplate.mask_dir'),
                    ('copyTempMask.out_dir', 'T2wTemplate.mask_dir')]),

                # File rename
                (Subjid, renameWarp1, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameWarp1, [
                    ('WarpSelect1.out', 'in_file')]),
                (Subjid, renameWarp2, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameWarp2, [
                    ('WarpSelect2.out', 'in_file')]),
                (Subjid, renameMask, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameMask, [
                    ('MaskTransform.out_file', 'in_file')]),
                (Subjid, renameDWINorm, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameDWINorm, [
                    ('DWITransform.out_file', 'in_file')]),
                (Subjid, renameDTI, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameDTI, [
                    ('FitTensor.out_file', 'in_file')]),
                (Subjid, renameFA, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameFA, [
                    ('TensorMetrics.out_fa', 'in_file')]),
                (Subjid, renameMD, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameMD, [
                    ('TensorMetrics.out_adc', 'in_file')]),
                (Subjid, renameAD, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameAD, [
                    ('TensorMetrics.out_ad', 'in_file')]),
                (Subjid, renameRD, [
                    ('subjid', 'subjid')]),
                (prepTensor_wf, renameRD, [
                    ('TensorMetrics.out_rd', 'in_file')]),
                (Subjid, renameT1w, [
                    ('subjid', 'subjid')]),
                (prepAnat_wf, renameT1w, [
                    ('t1wTransform.out_file', 'in_file')]),
                (Subjid, renameT2w, [
                    ('subjid', 'subjid')]),
                (prepAnat_wf, renameT2w, [
                    ('t2wTransform.out_file', 'in_file')]),

                # Output
                # Template sink
                (fodTemplate_wf, templateSink, [
                    ('FODTemplate.out_file', 'response.@template'),
                    ('avgResponse_csf.out_file', 'response.@csf'),
                    ('avgResponse_gm.out_file', 'response.@gm'),
                    ('avgResponse_wm.out_file', 'response.@wm')]),
                (tensorTemplate_wf, templateSink, [
                    ('MaskTemplate.out_file', 'dwi.@mask'),
                    ('FATemplate.out_file', 'dti.@fa'),
                    ('MDTemplate.out_file', 'dti.@md'),
                    ('ADTemplate.out_file', 'dti.@ad'),
                    ('RDTemplate.out_file', 'dti.@rd')]),
                (genTemplateTract_wf, templateSink, [
                    ('template_tcksift.out_file', 'tractography.@tck'),
                    ('template_tckconvert.out_file', 'tractography.@tract')]),
                (anatTemplate_wf, templateSink, [
                    ('T1wTemplate.out_file', 'anat.@t1w'),
                    ('T2wTemplate.out_file', 'anat.@t2w')]),

                # Subject Sink
                (Subjid, subjSink, [
                    ('subjid', 'container')]),
                (renameWarp1, subjSink, [
                    ('out_file', 'transform.@warp1')]),
                (renameWarp2, subjSink, [
                    ('out_file', 'transform.@warp2')]),
                (renameMask, subjSink, [
                    ('out_file', 'dwi.@mask')]),
                (renameDWINorm, subjSink, [
                    ('out_file', 'dwi.@data')]),
                (renameDTI, subjSink, [
                    ('out_file', 'dti.@tensor')]),
                (renameFA, subjSink, [
                    ('out_file', 'dti.@fa')]),
                (renameMD, subjSink, [
                    ('out_file', 'dti.@md')]),
                (renameAD, subjSink, [
                    ('out_file', 'dti.@ad')]),
                (renameRD, subjSink, [
                    ('out_file', 'dti.@rd')]),
                (renameT1w, subjSink, [
                    ('out_file', 'anat.@t1w')]),
                (renameT2w, subjSink, [
                    ('out_file', 'anat.@t2w')])
            ])

    pl.write_graph(graph2use='flat', format='svg', simple_form=False)
    pl.write_graph(graph2use='colored', format='svg')

    if nthreads >= 8:
        pl.run(plugin='MultiProc', plugin_args={'n_procs': 4})
    else:
        pl.run(plugin='Linear')


if __name__ == '__main__':
    main()
