name: MRTPipelines Docker Template

on:
  push:
    branches:
    - template

jobs:
  docker_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout correct branch
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    # Build and deploy docker dev image
    - name: Build & deploy MRTPipelines Docker base image
      if: github.ref == 'refs/heads/template'
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        echo 'Docker login'
        echo ''
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_KEY
        echo ''
        echo 'Building docker image...'
        echo ''
        cd container
        docker build . --tag $DOCKER_HUB_USER/mrtpipelines_template:latest
        echo ''
        echo 'Pushing docker image...'
        echo ''
        docker push $DOCKER_HUB_USER/mrtpipelines_template:latest
        echo ''
        echo 'Finished deploying docker image!'
