name: MRTPipelines Docker

on:
  push:
    branches:
    - master

jobs:
  docker_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout correct branch
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master

    # Build and deploy docker dev image
    - name: Build & deploy MRTPipelines Docker image
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
      run: |
        echo 'Docker login'
        echo ''
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_KEY
        echo ''
        echo 'Building docker image...'
        echo ''
        cd container
        docker build . --tag $DOCKER_HUB_USER/mrtpipelines:latest
        echo ''
        echo 'Pushing docker image...'
        echo ''
        docker push $DOCKER_HUB_USER/mrtpipelines:latest
        echo ''
        echo 'Finished deploying docker image!'
